Improvement on Detailed notification example
jazzyisj/unavailable-entities-sensor pull request #22
Opened 2022-10-04 01:39 UTC by warthog9

This extends the detailed notification example to combine entities into their respective devices, as well as link (at least tested on the actual web interface) to the entities' device.

Signed-off-by: John 'Warthog9' Hawley <warthog9@eaglescrag.net>

2022-10-04 02:42 UTC, jazzyisj requested changes
Very cool.  I think there is an issue with this function call though.

`device_attr(device_id(s.entity_id), "name")`

There can be entities in a config that do not have a device id so this will throw an error when the device_id(s.entity_id) call evaluates to null.

`TemplateError: str: Must provide a device or entity ID`

```
{% set ns = namespace(result=[]) %}
{% for s in expand(state_attr('sensor.unavailable_entities', 'entity_id')) %}
ID {{ device_id(s.entity_id) }} {{ s.entity_id }}
{% endfor %}
```
![image](https://user-images.githubusercontent.com/44064559/193722965-40dd53fb-7751-4e5b-9cbe-459375be88ce.png)

I'm not sure what the advantage to providing the device_id rather than just the entity_id to device_attr() is?  Changing the function call using the entity_id seems to accomplish what you were going for and every entity has one.  

`device_attr(s.entity_id, "name")`

Thoughts?

2022-10-04 04:32 UTC, warthog9 commented
device_attr(s.entity_id, "name") works for me as I'd expect, I thought I needed to pass it the device_id for the lookup to work right (yay that you don't!)

Also happened to double check and the URL worked fine for me from the Android app, so that was a pleasant surprise.  Give me a couple and I'll have an updated PR

2022-10-04 04:40 UTC, warthog9 commented
Give that a shot, works for me but I seemingly don't have an entity that's not associated to a device that's unavailable to confirm it's right in that case

2022-10-05 01:12 UTC, merged

2022-10-05 01:18 UTC, jazzyisj commented
Yep that works.  Thanks for the contribution!